# Generated by Django 2.1 on 2021-03-13 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbtitype', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalities.Classification')),
            ],
        ),
    ]
