# Generated by Django 2.1 on 2021-03-13 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personalities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personality',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
